package saleson.common.enumeration;

import saleson.common.enumeration.mapper.CodeMapperType;

public enum CountryCode implements CodeMapperType {
	AF("Afghanistan", "93", true),
	AL("Albania", "355", true),
	DZ("Algeria", "213", true),
	AS("American Samoa", "1", true),
	AD("Andorra", "376", true),
	AO("Angola", "244", true),
	AI("Anguilla", "1", true),
	AG("Antigua", "1", true),
	AR("Argentina", "54", true),
	AM("Armenia", "374", true),
	AW("Aruba", "297", true),
	AU("Australia", "61", true),
	AT("Austria", "43", true),
	AZ("Azerbaijan", "994", true),
	BH("Bahrain", "973", true),
	BD("Bangladesh", "880", true),
	BB("Barbados", "1", true),
	BY("Belarus", "375", true),
	BE("Belgium", "32", true),
	BZ("Belize", "501", true),
	BJ("Benin", "229", true),
	BM("Bermuda", "1", true),
	BT("Bhutan", "975", true),
	BO("Bolivia", "591", true),
	BQ("Bonaire, Sint Eustatius and Saba", "599", true),
	BA("Bosnia and Herzegovina", "387", true),
	BW("Botswana", "267", true),
	BR("Brazil", "55", true),
	IO("British Indian Ocean Territory", "246", true),
	VG("British Virgin Islands", "1", true),
	BN("Brunei", "673", true),
	BG("Bulgaria", "359", true),
	BF("Burkina Faso", "226", true),
	BI("Burundi", "257", true),
	KH("Cambodia", "855", true),
	CM("Cameroon", "237", true),
	CA("Canada", "1", true),
	CV("Cape Verde", "238", true),
	KY("Cayman Islands", "1", true),
	CF("Central African Republic", "236", true),
	TD("Chad", "235", true),
	CL("Chile", "56", true),
	CN("China", "86", true),
	CO("Colombia", "57", true),
	KM("Comoros", "269", true),
	CK("Cook Islands", "682", true),
	CR("Costa Rica", "506", true),
	CI("Côte d'Ivoire", "225", true),
	HR("Croatia", "385", true),
	CU("Cuba", "53", true),
	CW("Curaçao", "599", true),
	CY("Cyprus", "357", true),
	CZ("Czech Republic", "420", true),
	CD("Democratic Republic of the Congo", "243", true),
	DK("Denmark", "45", true),
	DJ("Djibouti", "253", true),
	DM("Dominica", "1", true),
	DO("Dominican Republic", "1", true),
	EC("Ecuador", "593", true),
	EG("Egypt", "20", true),
	SV("El Salvador", "503", true),
	GQ("Equatorial Guinea", "240", true),
	ER("Eritrea", "291", true),
	EE("Estonia", "372", true),
	ET("Ethiopia", "251", true),
	FK("Falkland Islands", "500", true),
	FO("Faroe Islands", "298", true),
	FM("Federated States of Micronesia", "691", true),
	FJ("Fiji", "679", true),
	FI("Finland", "358", true),
	FR("France", "33", true),
	GF("French Guiana", "594", true),
	PF("French Polynesia", "689", true),
	GA("Gabon", "241", true),
	GE("Georgia", "995", true),
	DE("Germany", "49", true),
	GH("Ghana", "233", true),
	GI("Gibraltar", "350", true),
	GR("Greece", "30", true),
	GL("Greenland", "299", true),
	GD("Grenada", "1", true),
	GP("Guadeloupe", "590", true),
	GU("Guam", "1", true),
	GT("Guatemala", "502", true),
	GG("Guernsey", "44", true),
	GN("Guinea", "224", true),
	GW("Guinea-Bissau", "245", true),
	GY("Guyana", "592", true),
	HT("Haiti", "509", true),
	HN("Honduras", "504", true),
	HK("Hong Kong", "852", true),
	HU("Hungary", "36", true),
	IS("Iceland", "354", true),
	IN("India", "91", true),
	ID("Indonesia", "62", true),
	IR("Iran", "98", true),
	IQ("Iraq", "964", true),
	IE("Ireland", "353", true),
	IM("Isle Of Man", "44", true),
	IL("Israel", "972", true),
	IT("Italy", "39", true),
	JM("Jamaica", "1", true),
	JP("Japan", "81", true),
	JE("Jersey", "44", true),
	JO("Jordan", "962", true),
	KZ("Kazakhstan", "7", true),
	KE("Kenya", "254", true),
	KI("Kiribati", "686", true),
	KW("Kuwait", "965", true),
	KG("Kyrgyzstan", "996", true),
	LA("Laos", "856", true),
	LV("Latvia", "371", true),
	LB("Lebanon", "961", true),
	LS("Lesotho", "266", true),
	LR("Liberia", "231", true),
	LY("Libya", "218", true),
	LI("Liechtenstein", "423", true),
	LT("Lithuania", "370", true),
	LU("Luxembourg", "352", true),
	MO("Macau", "853", true),
	MK("Macedonia", "389", true),
	MG("Madagascar", "261", true),
	MW("Malawi", "265", true),
	MY("Malaysia", "60", true),
	MV("Maldives", "960", true),
	ML("Mali", "223", true),
	MT("Malta", "356", true),
	MH("Marshall Islands", "692", true),
	MQ("Martinique", "596", true),
	MR("Mauritania", "222", true),
	MU("Mauritius", "230", true),
	YT("Mayotte", "262", true),
	MX("Mexico", "52", true),
	MD("Moldova", "373", true),
	MC("Monaco", "377", true),
	MN("Mongolia", "976", true),
	ME("Montenegro", "382", true),
	MS("Montserrat", "1", true),
	MA("Morocco", "212", true),
	MZ("Mozambique", "258", true),
	MM("Myanmar", "95", true),
	NA("Namibia", "264", true),
	NR("Nauru", "674", true),
	NP("Nepal", "977", true),
	NL("Netherlands", "31", true),
	NC("New Caledonia", "687", true),
	NZ("New Zealand", "64", true),
	NI("Nicaragua", "505", true),
	NE("Niger", "227", true),
	NG("Nigeria", "234", true),
	NU("Niue", "683", true),
	NF("Norfolk Island", "672", true),
	KP("North Korea", "850", true),
	MP("Northern Mariana Islands", "1", true),
	NO("Norway", "47", true),
	OM("Oman", "968", true),
	PK("Pakistan", "92", true),
	PW("Palau", "680", true),
	PS("Palestine", "970", true),
	PA("Panama", "507", true),
	PG("Papua New Guinea", "675", true),
	PY("Paraguay", "595", true),
	PE("Peru", "51", true),
	PH("Philippines", "63", true),
	PL("Poland", "48", true),
	PT("Portugal", "351", true),
	PR("Puerto Rico", "1", true),
	QA("Qatar", "974", true),
	CG("Republic of the Congo", "242", true),
	RE("Réunion", "262", true),
	RO("Romania", "40", true),
	RU("Russia", "7", true),
	RW("Rwanda", "250", true),
	SH("Saint Helena", "290", true),
	KN("Saint Kitts and Nevis", "1", true),
	PM("Saint Pierre and Miquelon", "508", true),
	VC("Saint Vincent and the Grenadines", "1", true),
	WS("Samoa", "685", true),
	SM("San Marino", "378", true),
	ST("Sao Tome and Principe", "239", true),
	SA("Saudi Arabia", "966", true),
	SN("Senegal", "221", true),
	RS("Serbia", "381", true),
	SC("Seychelles", "248", true),
	SL("Sierra Leone", "232", true),
	SG("Singapore", "65", true),
	SX("Sint Maarten", "1", true),
	SK("Slovakia", "421", true),
	SI("Slovenia", "386", true),
	SB("Solomon Islands", "677", true),
	SO("Somalia", "252", true),
	ZA("South Africa", "27", true),
	KR("South Korea", "82", true),
	SS("South Sudan", "211", true),
	ES("Spain", "34", true),
	LK("Sri Lanka", "94", true),
	LC("St. Lucia", "1", true),
	SD("Sudan", "249", true),
	SR("Suriname", "597", true),
	SZ("Swaziland", "268", true),
	SE("Sweden", "46", true),
	CH("Switzerland", "41", true),
	SY("Syria", "963", true),
	TW("Taiwan", "886", true),
	TJ("Tajikistan", "992", true),
	TZ("Tanzania", "255", true),
	TH("Thailand", "66", true),
	BS("The Bahamas", "1", true),
	GM("The Gambia", "220", true),
	TL("Timor-Leste", "670", true),
	TG("Togo", "228", true),
	TK("Tokelau", "690", true),
	TO("Tonga", "676", true),
	TT("Trinidad and Tobago", "1", true),
	TN("Tunisia", "216", true),
	TR("Turkey", "90", true),
	TM("Turkmenistan", "993", true),
	TC("Turks and Caicos Islands", "1", true),
	TV("Tuvalu", "688", true),
	UG("Uganda", "256", true),
	UA("Ukraine", "380", true),
	AE("United Arab Emirates", "971", true),
	GB("United Kingdom", "44", true),
	US("United States", "1", true),
	UY("Uruguay", "598", true),
	VI("US Virgin Islands", "1", true),
	UZ("Uzbekistan", "998", true),
	VU("Vanuatu", "678", true),
	VE("Venezuela", "58", true),
	VN("Vietnam", "84", true),
	WF("Wallis and Futuna", "681", true),
	EH("Western Sahara", "212", true),
	YE("Yemen", "967", true),
	ZM("Zambia", "260", true)
		;

	private String title;
	private Boolean enabled;
	private String dialingCode;

	CountryCode(String title, String dialingCode, boolean enabled) {
		this.title = title;
		this.dialingCode = dialingCode;
		this.enabled = enabled;

	}


	@Override
	public String getCode() {
		return name();
	}

	@Override
	public String getTitle() {
		return title;
	}

	@Override
	public String getDescription() {
		return dialingCode;
	}
	@Override
	public Boolean isEnabled() {
		return enabled;
	}
}
