on:
  pull_request:
  issue_comment:

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'translation-update-') }}
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.AGENT_PR_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_action.auto_review: "false" # enable\disable auto review
          github_action.auto_describe: "true" # enable\disable auto describe
          github_action.auto_improve: "false" # enable\disable auto improve