BEGIN;
ALTER TABLE COUNTER ADD COLUMN `ENABLED` varchar(1) DEFAULT 'Y';
UPDATE COUNTER SET ENABLED='Y' WHERE ENABLED IS NULL;
ALTER TABLE TERMINAL ADD COLUMN `ENABLED` varchar(1) DEFAULT 'Y';
UPDATE TERMINAL SET ENABLED='Y' WHERE ENABLED IS NULL;
ALTER TABLE `ROLE` ADD COLUMN `ENABLED` varchar(1) DEFAULT 'Y';
UPDATE `ROLE` SET ENABLED='Y' WHERE ENABLED IS NULL;
COMMIT;