BEGIN;
DELETE FROM `CUSTOM_FIELD_VALUE`
WHERE `CUSTOM_FIELD_ID` in (SELECT `ID` FROM `CUSTOM_FIELD` WHERE `OBJECT_TYPE`='TOOLING' AND `PROPERTY_GROUP` is null)
AND `ID`>0;
DELETE FROM CUSTOM_FIELD WHERE OBJECT_TYPE='TOOLING' AND PROPERTY_GROUP IS NULL AND ID>0;
COMMIT;