DROP TABLE IF EXISTS `V_PART_TARGET_UPTIME_HOUR`;

CREATE OR REPLACE VIEW `V_PART_TARGET_UPTIME_HOUR` as
SELECT MP.PART_ID as ID,
       SUM(CASE
               WHEN M.SHIFTS_PER_DAY IS NOT NULL THEN CAST(M.SHIFTS_PER_DAY AS SIGNED)
               ELSE 24
               END) AS HOUR_PER_DAY  FROM MOLD_PART MP INNER JOIN MOLD M ON MP.MOLD_ID=M.ID AND M.DELETED <> 'Y'
GROUP BY MP.PART_ID
;

DROP TABLE IF EXISTS `V_COMPANY_TARGET_UPTIME_HOUR`;

CREATE OR REPLACE VIEW `V_COMPANY_TARGET_UPTIME_HOUR` as
SELECT M.COMPANY_ID as ID,
       SUM(CASE
               WHEN M.SHIFTS_PER_DAY IS NOT NULL THEN CAST(M.SHIFTS_PER_DAY AS SIGNED)
               ELSE 24
               END) AS HOUR_PER_DAY  FROM  MOLD M
       WHERE M.DELETED <> 'Y'
GROUP BY M.COMPANY_ID
;
