BEGIN;
ALTER TABLE `WORK_ORDER`
    ADD COLUMN REQUEST_APPROVAL_ENABLED VARCHAR(1) DEFAULT NULL;
UPDATE `WORK_ORDER`
SET REQUEST_APPROVAL_ENABLED = 'Y';

ALTER TABLE `WORK_ORDER`
    ADD COLUMN REJECTED_BY_ID BIGINT DEFAULT NULL;
ALTER TABLE `WORK_ORDER`
    ADD COLUMN REJECTED_REASON LONGTEXT DEFAULT NULL;

COMMIT;