BEGIN;
CREATE TABLE IF NOT EXISTS CHART_TYPE_CONFIG(
    `ID` bigint(20) AUTO_INCREMENT NOT NULL,
    `CREATED_AT` datetime DEFAULT NOW(),
    `UPDATED_AT` datetime DEFAULT NOW(),
    `CHART_DATA_TYPE` varchar(20) DEFAULT NULL,
    `CHART_TYPE` varchar(20) DEFAULT NULL,
    `USER_ID` bigint(20) NOT NULL,
    PRIMARY KEY (`ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
COMMIT;