BEGIN;
DROP TABLE IF EXISTS `DATA_REGISTRATION_OBJECT`;
CREATE TABLE `DATA_REGISTRATION_OBJECT`
(
    `ID`                   BIGINT NOT NULL AUTO_INCREMENT,
    `DATA_REGISTRATION_ID` BIGINT      DEFAULT NULL,
    `OBJECT_TYPE`          VARCHAR(50) DEFAULT NULL,
    `OBJECT_ID`            BIGINT      DEFAULT NULL,
    `CREATED_AT`           DATETIME    DEFAULT NULL,
    `UPDATED_AT`           DATETIME    DEFAULT NULL,
    PRIMARY KEY (`ID`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = utf8mb4;
COMMIT;