DROP TABLE IF EXISTS ROLE_USER;

CREATE TABLE ROLE_USER (
	ID bigint not null auto_increment,
	
	ROLE_ID bigint,
	LOCATION_ID bigint(19),
	USER_ID bigint,
	
	CREATED_BY bigint,
	CREATED_AT datetime,
	
	PRIMARY KEY (ID)
) CHARSET=utf8;

ALTER TABLE ROLE_USER
	ADD CONSTRAINT FK_ROLE_USER 
	FOREIGN KEY (ROLE_ID) 
	REFERENCES ROLE (ID);

ALTER TABLE ROLE_USER
	ADD CONSTRAINT FK_ROLE_USER_02
	FOREIGN KEY (LOCATION_ID) 
	REFERENCES LOCATION (ID);

ALTER TABLE ROLE_USER
	ADD CONSTRAINT FK_ROLE_USER_03
	FOREIGN KEY (USER_ID) 
	REFERENCES `USER` (ID);

ALTER TABLE ROLE_USER
	ADD CONSTRAINT UX_ROLE_USER 
	UNIQUE (
		ROLE_ID, 
		LOCATION_ID, 
		USER_ID
	);


DROP TABLE IF EXISTS PERMISSION;

CREATE TABLE PERMISSION (
	ID bigint not null auto_increment,
	
	ROLE_ID bigint,
	RESOURCE_TYPE varchar(50),
	RESOURCE_ID varchar(100),
	ENABLED varchar(1),
	
	CREATED_BY bigint,
	CREATED_AT datetime,
	UPDATED_BY bigint,
	UPDATED_AT datetime,
	
	PRIMARY KEY (ID)
) CHARSET=utf8;

ALTER TABLE PERMISSION
	ADD CONSTRAINT FK_PERMISSION
	FOREIGN KEY (ROLE_ID)
	REFERENCES ROLE (ID);

ALTER TABLE PERMISSION
	ADD CONSTRAINT UX_PERMISSION 
	UNIQUE (
		ROLE_ID, 
		RESOURCE_TYPE, 
		RESOURCE_ID
	);