BEGIN;
ALTER TABLE PRODUCED_PART ADD COLUMN `WEEK` VARCHAR(255) DEFAULT NULL;
ALTER TABLE PRODUCED_PART ADD COLUMN `MONTH` VARCHAR(255) DEFAULT NULL;
ALTER TABLE PRODUCED_PART ADD COLUMN `FREQUENT` VARCHAR(255) DEFAULT NULL;

UPDATE PRODUCED_PART SET FREQUENT = 'DAILY';
COMMIT;