BEGIN;
ALTER TABLE `WORK_ORDER` ADD COLUMN REJECTED_CHANGE_BY_ID BIGINT DEFAULT NULL;
ALTER TABLE `WORK_ORDER` ADD COLUMN DECLINED_BY_ID BIGINT DEFAULT NULL;
ALTER TABLE `WORK_ORDER` ADD COLUMN CANCELED_BY_ID BIGINT DEFAULT NULL;
COMMIT;