BEGIN ;

DROP TABLE IF EXISTS `CYCLE_TIME_FLUCTUATION`;

CREATE TABLE `CYCLE_TIME_FLUCTUATION` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT,

	`SUPPLIER_ID` BIGINT,
	`MOLD_ID` BIGINT,
	`PART_ID` BIGINT,

	`TIME_SCALE` VARCHAR(255),
	`YEAR` VARCHAR(255),
	`MONTH` VARCHAR(255),
	`WEEK` VARCHAR(255),
	`DAY` VARCHAR(255),

	`APPROVED_CYCLE_TIME` DOUBLE,
	`AVERAGE_CYCLE_TIME` DOUBLE,
    `NCTF` DOUBLE DEFAULT NULL,
    `L1_LIMIT` DOUBLE DEFAULT NULL,
    `CT_FLUCTUATION` DOUBLE DEFAULT NULL,
    `CTF_TREND` DOUBLE DEFAULT NULL,

	`SHOT_COUNT` INT,

	`CREATED_AT` DATETIME,
	`UPDATED_AT` DATETIME,

	PRIMARY KEY (`ID`)
) DEFAULT CHARSET = UTF8MB4;

COMMIT ;
