BEGIN;
# DROP TABLE IF EXISTS `SHIFT_CONFIG`;
# CREATE TABLE SHIFT_CONFIG
# (
#     `ID`          BIGINT(20) AUTO_INCREMENT NOT NULL,
#     `CREATED_AT`  DATETIME DEFAULT NOW(),
#     `UPDATED_AT`  DATETIME DEFAULT NOW(),
#     `CREATED_BY`  BIGINT   DEFAULT NULL,
#     `UPDATED_BY`  BIGINT   DEFAULT NULL,
#     `LOCATION_ID` BIGINT(20)                NOT NULL,
#     PRIMARY KEY (`ID`),
#     KEY `IDX_LOCATION_ID` (`LOCATION_ID`)
# ) ENGINE = InnoDB
#   DEFAULT CHARSET = utf8;


DROP TABLE IF EXISTS `DAY_SHIFT`;
CREATE TABLE DAY_SHIFT
(
    `ID`               BIGINT(20) AUTO_INCREMENT NOT NULL,
    `CREATED_AT`       DATETIME    DEFAULT NOW(),
    `UPDATED_AT`       DATETIME    DEFAULT NOW(),
    `CREATED_BY`       BIGINT      DEFAULT NULL,
    `UPDATED_BY`       BIGINT      DEFAULT NULL,
    `LOCATION_ID`      BIGINT(20)                NOT NULL,
    `NUMBER_OF_SHIFTS` BIGINT(20)  DEFAULT NULL,
    `START`        VARCHAR(20) DEFAULT NULL,
    `END`          VARCHAR(20) DEFAULT NULL,
    `DAY_SHIFT_TYPE`   VARCHAR(20) DEFAULT NULL,
    `AUTOMATIC`        VARCHAR(1)  DEFAULT 'Y',
    PRIMARY KEY (`ID`),
    KEY `IDX_LOCATION_ID` (`LOCATION_ID`),
    KEY `IDX_DAY_SHIFT_TYPE` (`DAY_SHIFT_TYPE`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;


DROP TABLE IF EXISTS `HOUR_SHIFT`;
CREATE TABLE HOUR_SHIFT
(
    `ID`           BIGINT(20) AUTO_INCREMENT NOT NULL,
    `CREATED_AT`   DATETIME    DEFAULT NOW(),
    `UPDATED_AT`   DATETIME    DEFAULT NOW(),
    `CREATED_BY`   BIGINT      DEFAULT NULL,
    `UPDATED_BY`   BIGINT      DEFAULT NULL,
    `DAY_SHIFT_ID` BIGINT(20)  DEFAULT NULL,
    `SHIFT_NUMBER` BIGINT(20)  DEFAULT NULL,
    `START`        VARCHAR(20) DEFAULT NULL,
    `END`          VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (`ID`),
    KEY `IDX_DAY_SHIFT_ID` (`DAY_SHIFT_ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;
COMMIT;