BEGIN ;
DROP TABLE IF EXISTS `SYSTEM_NOTE_READ`;
CREATE TABLE `SYSTEM_NOTE_READ`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `SYSTEM_NOTE_ID` BIGINT,
    `USER_ID` BIGINT,
    `IS_READ` VARCHAR(1) DEFAULT 'Y',
    `CREATED_AT` datetime DEFAULT NOW(),

    PRIMARY KEY (`ID`)
) DEFAULT CHARSET = UTF8MB4;
create index IDX_USER_ID__SYSTEM_NOTE_READ on SYSTEM_NOTE_READ (USER_ID);
create index IDX_USER_ID_SYSTEM_NOTE_ID__SYSTEM_NOTE_READ on SYSTEM_NOTE_READ (USER_ID, SYSTEM_NOTE_ID);

COMMIT ;
