BEGIN;
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `MACHINE_STATISTICS` MODIFY DAILY_WORKING_HOUR_NOTE LONGTEXT;
ALTER TABLE `MACHINE_STATISTICS` MODIFY PLANNED_DOWNTIME_NOTE LONGTEXT;
ALTER TABLE `MACHINE_STATISTICS` MODIFY UNPLANNED_DOWNTIME_NOTE LONGTEXT;
SET FOREIGN_KEY_CHECKS=1;
COMMIT;