BEGIN;
CREATE TABLE IF NOT EXISTS USER_GRAPH_SETTINGS_CONFIG(
    `ID` bigint(20) AUTO_INCREMENT NOT NULL,
    `USER_ID` bigint(20) NOT NULL,
    `CREATED_AT` datetime DEFAULT NOW(),
    `UPDATED_AT` datetime DEFAULT NOW(),
    `CHART_DATA_TYPE` varchar(20) DEFAULT NULL,
    `GRAPH_ITEM_TYPE` varchar(20) DEFAULT NULL,
    `SELECTED` varchar(1) DEFAULT 'Y',
    PRIMARY KEY (`ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE USER_GRAPH_SETTINGS_CONFIG
   ADD CONSTRAINT UNQ_USER_GRAPH_SETTINGS_CONFIG UNIQUE (USER_ID, CHART_DATA_TYPE, GRAPH_ITEM_TYPE);
CREATE INDEX IDX_USER_GRAPH_SETTINGS_CONFIG ON USER_GRAPH_SETTINGS_CONFIG (
	USER_ID,
	CHART_DATA_TYPE
);

COMMIT;