BEGIN;
DROP TABLE IF EXISTS `RESIN_CODE_CHANGE`;
CREATE TABLE `RESIN_CODE_CHANGE`
(
    `ID`             BIGINT NOT NULL AUTO_INCREMENT,
    `PART_ID`        BIGINT      DEFAULT NULL,
    `OLD_RESIN_CODE` LONGTEXT    DEFAULT NULL,
    `NEW_RESIN_CODE` LONGTEXT    DEFAULT NULL,
    `TIME`           DATETIME    DEFAULT NULL,
    `MONTH`          VARCHAR(20) DEFAULT NULL,
    `WEEK`           VARCHAR(20) DEFAULT NULL,
    `DAY`            VARCHAR(20) DEFAULT NULL,
    `HOUR`           VARCHAR(20) DEFAULT NULL,
    `CURRENT_WACT`   DOUBLE      DEFAULT NULL,
    `CREATED_AT`     DATETIME    DEFAULT NULL,
    `UPDATED_AT`     DATETIME    DEFAULT NULL,
    PRIMARY KEY (`ID`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = utf8mb4;
COMMIT;