BEGIN;
ALTER TABLE `MACHINE_OEE` ADD COLUMN TEN_MINUTE VARCHAR(20) DEFAULT NULL;
ALTER TABLE `MACHINE_OEE` ADD COLUMN PERIOD_TYPE VARCHAR(20) DEFAULT NULL;

UPDATE `MACHINE_OEE` SET PERIOD_TYPE = 'HOURLY';
UPDATE `MACHINE_OEE` SET TEN_MINUTE = CONCAT(HOUR,'5');
COMMIT;