BEGIN;
CREATE TABLE IF NOT EXISTS DASHBOARD_SETTING(
    `ID` bigint(20) AUTO_INCREMENT NOT NULL,
    `CREATED_AT` datetime DEFAULT NOW(),
    `UPDATED_AT` datetime DEFAULT NOW(),
    `CREATED_BY` bigint(20) DEFAULT NULL,
    `UPDATED_BY` bigint(20) DEFAULT NULL,
    `DELETED` varchar(1) DEFAULT 'N',
    `LEVEL` varchar(20) DEFAULT NULL,
    `MONTH_NUMBER` INT DEFAULT NULL,
    `USER_ID` bigint(20) NOT NULL,
    PRIMARY KEY (`ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
COMMIT;