BEGIN;
CREATE TABLE IF NOT EXISTS DASHBOARD_CHART_DISPLAY_SETTING(
    `ID` bigint(20) AUTO_INCREMENT NOT NULL,
    `CREATED_AT` datetime DEFAULT NOW(),
    `UPDATED_AT` datetime DEFAULT NOW(),
    `CREATED_BY` bigint(20) DEFAULT NULL,
    `UPDATED_BY` bigint(20) DEFAULT NULL,
    `DELETED` varchar(1) DEFAULT 'N',
    `CHART_TYPE` varchar(50),
    `USER_ID` bigint(20) NOT NULL,
    PRIMARY KEY (`ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS DASHBOARD_CHART_PARAM_SETTING(
    `ID` bigint(20) AUTO_INCREMENT NOT NULL,
    `DASHBOARD_CHART_DISPLAY_SETTING_ID` bigint(20) NOT NULL,
    `CREATED_AT` datetime DEFAULT NOW(),
    `UPDATED_AT` datetime DEFAULT NOW(),
    `CREATED_BY` bigint(20) DEFAULT NULL,
    `UPDATED_BY` bigint(20) DEFAULT NULL,
    `PARAM_NAME` varchar(50) DEFAULT 'N',
    `PARAM_VALUE` varchar(50) DEFAULT 'N',
    PRIMARY KEY (`ID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
COMMIT;