BEGIN ;
ALTER TABLE `MACHINE_MOLD_MATCHING_HISTORY` ADD COLUMN `MATCH_HOUR` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `MACHINE_MOLD_MATCHING_HISTORY` ADD COLUMN `UNMATCH_HOUR` VARCHAR(255) DEFAULT NULL;

update MACHINE_MOLD_MATCHING_HISTORY set MATCH_HOUR = DATE_FORMAT(MACHINE_MOLD_MATCHING_HISTORY.MATCH_TIME,"%H%i") where MACHINE_MOLD_MATCHING_HISTORY.MATCH_TIME is not null;
update MACHINE_MOLD_MATCHING_HISTORY set UNMATCH_HOUR = DATE_FORMAT(MACHINE_MOLD_MATCHING_HISTORY.UNMATCH_TIME,"%H%i") where MACHINE_MOLD_MATCHING_HISTORY.UNMATCH_TIME is not null;
COMMIT ;