BEGIN;
ALTER TABLE MOLD_MAINTENANCE ADD COLUMN ACCUMULATED_SHOT INT DEFAULT NULL;
ALTER TABLE MOLD_MAINTENANCE ADD COLUMN WORK_ORDER_ID BIGINT DEFAULT NULL;
ALTER TABLE WORK_ORDER ADD COLUMN MOLD_MAINTENANCE_ID BIGINT DEFAULT NULL;
COMMIT;