DROP TABLE IF EXISTS `MOLD_STANDARD_VALUE`;

CREATE TABLE MOLD_STANDARD_VALUE (
	ID bigint not null,
	CREATED_AT datetime,
	UPDATED_AT datetime,
	MOLD_ID bigint,
	MONTH varchar(255),
	PERIOD_MONTHS int(2),
	MIN_CDATA_COUNT int(6),
	MAX_CDATA_COUNT int(6),
	CDATA_COUNT int(6),
	STANDARD_VALUE double,
	PRIMARY KEY (ID)
);

ALTER TABLE MOLD_STANDARD_VALUE
   ADD CONSTRAINT UX_MOLD_STANDARD_VALUE UNIQUE (MOLD_ID, MONTH, PERIOD_MONTHS, MIN_CDATA_COUNT, MAX_CDATA_COUNT);

ALTER TABLE MOLD_STANDARD_VALUE
	ADD CONSTRAINT FK_MOLD_STANDARD_VALUE
		FOREIGN KEY (MOLD_ID)
		REFERENCES MOLD (ID)
