DROP TABLE IF EXISTS `OPTION_FIELD_VALUE`;

CREATE TABLE OPTION_FIELD_VALUE (
	ID bigint not null,
	CONFIG_CATEGORY varchar(255),
	DATA_TYPE varchar(255),
	FIELD_NAME varchar(255),
	POSITION integer not null,
	`VALUE` varchar(255),
	`DELETED` varchar(1),
	PRIMARY KEY (ID)
);

ALTER TABLE OPTION_FIELD_VALUE
   ADD CONSTRAINT UX_OPTION_FIELD_VALUE UNIQUE (CONFIG_CATEGORY, FIELD_NAME);
