BEGIN;
    ALTER TABLE CATEGORY ADD COLUMN `GRAND_PARENT_ID` bigint(20);
    ALTER TABLE CATEGORY ADD COLUMN `DIVISION` varchar(1000);
    UPDATE CATEGORY SET GRAND_PARENT_ID = PARENT_ID WHERE PARENT_ID IS NOT NULL;
    UPDATE CATEGORY SET PARENT_ID = NULL WHERE PARENT_ID IS NOT NULL;
    UPDATE CATEGORY SET LEVEL = 3 WHERE LEVEL = 2;

    INSERT INTO CATEGORY (ID,CREATED_AT,UPDATED_AT,DESCRIPTION,ENABLED,`LEVEL`,NAME) VALUES
    (0,now(),now(),'No Category','Y',1,'No Category');

COMMIT;