BEGIN;
ALTER TABLE MOLD ADD COLUMN WEIGHTED_AVERAGE_CYCLE_TIME DOUBLE DEFAULT NULL;
#update data for new field
UPDATE MOLD m1 INNER JOIN
    (SELECT m.ID, SUM(s.SHOT_COUNT*s.CT)/SUM(s.SHOT_COUNT) AS wact
     FROM MOLD m
     LEFT JOIN STATISTICS s ON s.MOLD_ID = m.ID
     GROUP BY m.ID, m.EQUIPMENT_CODE
     HAVING SUM(s.SHOT_COUNT) <> 0) a ON a.ID = m1.ID
SET m1.WEIGHTED_AVERAGE_CYCLE_TIME = a.wact;
COMMIT;