BEGIN;
DELETE FROM MENU WHERE ID = 1500;
INSERT INTO MENU (ID, CREATED_AT, UPDATED_AT, ADMIN_MENU, ENABLED, LEVEL, MENU_NAME, PARENT_ID, POSITION)
VALUES(1500, NOW(), NOW(), 'Y', 'Y', 2, 'Oee', 1000, 3) ;
COMMIT;