BEGIN ;

DROP TABLE IF EXISTS `TABBED_OVERVIEW_GENERAL_FILTER`;
CREATE TABLE TABBED_OVERVIEW_GENERAL_FILTER
(
    `ID`               BIGINT NOT NULL,
    `CREATED_AT`       DATETIME    DEFAULT NOW(),
    `UPDATED_AT`       DATETIME    DEFAULT NOW(),
    ALL_PRODUCT   VARCHAR(1) NULL,
    ALL_PART       VARCHAR(1) NULL,
    ALL_TOOLING VARCHAR(1) NULL,
    ALL_SUPPLIER   VARCHAR(1) NULL,
    USER_ID        BIGINT     NULL,
    DURATION        INT     NULL,
    CONSTRAINT FK_TABBED_OVERVIEW_GENERAL_FILTER_USER_ID
        FOREIGN KEY (USER_ID) REFERENCES USER (ID)
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8;

DROP TABLE IF EXISTS `TABBED_OVERVIEW_GENERAL_FILTER_PART`;
CREATE TABLE TABBED_OVERVIEW_GENERAL_FILTER_PART
(
    TABBED_OVERVIEW_GENERAL_FILTER_ID BIGINT NOT NULL,
    PART_ID                           BIGINT NOT NULL
);


DROP TABLE IF EXISTS `TABBED_OVERVIEW_GENERAL_FILTER_PRODUCT`;
CREATE TABLE TABBED_OVERVIEW_GENERAL_FILTER_PRODUCT
(
    TABBED_OVERVIEW_GENERAL_FILTER_ID BIGINT NOT NULL,
    PRODUCT_ID                        BIGINT NOT NULL
);


DROP TABLE IF EXISTS `TABBED_OVERVIEW_GENERAL_FILTER_SUPPLIER`;
CREATE TABLE TABBED_OVERVIEW_GENERAL_FILTER_SUPPLIER
(
    TABBED_OVERVIEW_GENERAL_FILTER_ID BIGINT NOT NULL,
    SUPPLIER_ID                       BIGINT NOT NULL
);


DROP TABLE IF EXISTS `TABBED_OVERVIEW_GENERAL_FILTER_TOOLING`;
CREATE TABLE TABBED_OVERVIEW_GENERAL_FILTER_TOOLING
(
    TABBED_OVERVIEW_GENERAL_FILTER_ID BIGINT NOT NULL,
    TOOLING_ID                        BIGINT NOT NULL
);

COMMIT ;
