BEGIN;
UPDATE
MOLD
SET
UTILIZATION_RATE = ROUND(LAST_SHOT * 100 / DESIGNED_SHOT)
WHERE
ROUND(LAST_SHOT * 100 / DESIGNED_SHOT) <> UTILIZATION_RATE
AND(ROUND(LAST_SHOT * 100 / DESIGNED_SHOT) - 1) <> UTILIZATION_RATE
AND DESIGNED_SHOT <> 0 AND DESIGNED_SHOT IS NOT NULL AND LAST_SHOT IS NOT NULL;
COMMIT;