DROP TABLE IF EXISTS PART_ORDER;

DROP TABLE IF EXISTS PART_PLAN;

CREATE TABLE PART_PLAN (
	ID bigint not null auto_increment,
	
	PRODUCT_ID bigint,
	PART_ID bigint,
	SUPPLIER_ID bigint,
	
	PERIOD_TYPE varchar(20),
	PERIOD_VALUE varchar(20),
	QUANTITY bigint,
	
	CREATED_BY bigint,
	CREATED_AT datetime,
	UPDATED_BY bigint,
	UPDATED_AT datetime,
	
	PRIMARY KEY (ID)
) CHARSET=utf8;

ALTER TABLE PART_PLAN
	ADD CONSTRAINT FK_PART_PLAN_PRODUCT
	FOREIGN KEY (PRODUCT_ID)
	REFERENCES CATEGORY (ID);

ALTER TABLE PART_PLAN
	ADD CONSTRAINT FK_PART_PLAN_PART
	FOREIGN KEY (PART_ID)
	REFERENCES PART (ID);

ALTER TABLE PART_PLAN
	ADD CONSTRAINT FK_PART_PLAN_SUPPLIER
	FOREIGN KEY (SUPPLIER_ID)
	REFERENCES COMPANY (ID);

ALTER TABLE PART_PLAN
	ADD CONSTRAINT UX_PART_PLAN
	UNIQUE (PRODUCT_ID, PART_ID, SUPPLIER_ID, PERIOD_TYPE, PERIOD_VALUE);