BEGIN;
ALTER TABLE MACHINE_DOWNTIME_ALERT ADD COLUMN LATEST VARCHAR(1);

UPDATE MACHINE_DOWNTIME_ALERT SET LATEST = 'Y' WHERE DOWNTIME_STATUS in ('DOWNTIME', 'REGISTERED');

UPDATE MACHINE_DOWNTIME_ALERT as mda INNER JOIN (SELECT
			MAX(ID) as ID
		FROM MACHINE_DOWNTIME_ALERT
		WHERE
			DOWNTIME_STATUS IN('CONFIRMED', 'UNCONFIRMED')
		GROUP BY
			MACHINE_ID) as tb1 on tb1.ID = mda.ID
SET mda.LATEST = 'Y';
COMMIT;