BEGIN;
DROP TABLE IF EXISTS `DOWNTIME_ITEM`;
CREATE TABLE `DOWNTIME_ITEM`
(
    `ID`                    bigint(20) NOT NULL AUTO_INCREMENT,
    `CREATED_AT`            datetime     DEFAULT NULL,
    `UPDATED_AT`            datetime     DEFAULT NULL,
    `CREATED_BY`            bigint(20) DEFAULT NULL,
    `UPDATED_BY`            bigint(20) DEFAULT NULL,
    `TYPE`                  varchar(255) DEFAULT NULL,
    `HOUR_FROM`             int(11) DEFAULT NULL,
    `HOUR_TO`               int(11) DEFAULT NULL,
    `MINUTE_FROM`           int(11) DEFAULT NULL,
    `MINUTE_TO`             int(11) DEFAULT NULL,
    `REASON`                  varchar(255) DEFAULT NULL,
    `NOTE`                  longtext,
    `MACHINE_STATISTICS_ID` bigint(20) DEFAULT NULL,
    PRIMARY KEY (`ID`),
    KEY                     `FK-downtime-item-machine-statistics` (`MACHINE_STATISTICS_ID`),
    CONSTRAINT `FK-downtime-item-machine-statistics` FOREIGN KEY (`MACHINE_STATISTICS_ID`) REFERENCES `MACHINE_STATISTICS` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1562 DEFAULT CHARSET=utf8;

#new column for saving minute
ALTER TABLE `MACHINE_STATISTICS` ADD COLUMN DAILY_WORKING_HOUR_MINUTE int(11) DEFAULT NULL;
ALTER TABLE `MACHINE_STATISTICS` ADD COLUMN PLANNED_DOWNTIME_MINUTE int(11) DEFAULT NULL;
ALTER TABLE `MACHINE_STATISTICS` ADD COLUMN UNPLANNED_DOWNTIME_MINUTE int(11) DEFAULT NULL;

#drop unused columns
ALTER TABLE `MACHINE_STATISTICS` DROP COLUMN PLANNED_DOWNTIME_FROM;
ALTER TABLE `MACHINE_STATISTICS` DROP COLUMN PLANNED_DOWNTIME_TO;
ALTER TABLE `MACHINE_STATISTICS` DROP COLUMN UNPLANNED_DOWNTIME_FROM;
ALTER TABLE `MACHINE_STATISTICS` DROP COLUMN UNPLANNED_DOWNTIME_TO;
COMMIT;