BEGIN;

DROP TABLE IF EXISTS `FILE_GROUP`;

CREATE TABLE IF NOT EXISTS FILE_GROUP (
	`ID` BIGINT AUTO_INCREMENT NOT NULL,
	
	`FILE_GROUP_KEY` VARCHAR(500),
	`PARAM_NAME` VARCHAR(100),
	`VERSION` VARCHAR(50),
	`VERSION_NO` BIGINT,
	`FILE_GROUP_STATUS` VARCHAR(20),
	
	`FILE_GROUP_TYPE` VARCHAR(50),
	`FILE_GROUP_CODE` VARCHAR(600),
	`FILE_GROUP_NAME` VARCHAR(100),
	`DESCRIPTION` VARCHAR(1000),
	`RELEASED_AT` DATETIME,
	
	`ENABLED` VARCHAR(1),
	
	`PREFIX` VARCHAR(50),
	`FILE_GROUP_KEY1` VARCHAR(100),
	`FILE_GROUP_KEY2` VARCHAR(100),
	`FILE_GROUP_KEY3` VARCHAR(100),
	`FILE_GROUP_KEY4` VARCHAR(100),
	`FILE_GROUP_KEY5` VARCHAR(100),
	
	`CREATED_BY` BIGINT,
	`CREATED_AT` DATETIME,
	`UPDATED_BY` BIGINT,
	`UPDATED_AT` DATETIME,
	
	PRIMARY KEY (`ID`)
) DEFAULT CHARSET=UTF8;

ALTER TABLE FILE_GROUP
   ADD CONSTRAINT UX_FILE_GROUP UNIQUE (FILE_GROUP_KEY, PARAM_NAME, VERSION);
ALTER TABLE FILE_GROUP
   ADD CONSTRAINT UX_FILE_GROUP2 UNIQUE (FILE_GROUP_TYPE, FILE_GROUP_CODE, VERSION);


DROP TABLE IF EXISTS `FILE_ITEM`;

CREATE TABLE IF NOT EXISTS FILE_ITEM(
	`ID` BIGINT AUTO_INCREMENT NOT NULL,
	
	`FILE_GROUP_KEY` VARCHAR(500),
	`PARAM_NAME` VARCHAR(100),
	`VERSION` VARCHAR(50),
	`POSITION` INTEGER,
	`FILE_NAME` VARCHAR(500),
	`FILE_STATUS` VARCHAR(20),
	
	`FILE_TYPE` VARCHAR(50),
	`FILE_NO` VARCHAR(600),
	`DESCRIPTION` VARCHAR(1000),
	`CONTENT_TYPE` VARCHAR(50),
	`FILE_SIZE` BIGINT,
	`STORAGE_TYPE` VARCHAR(20),
	`FILE_LOCATION` VARCHAR(1000),
	
	`CREATED_BY` BIGINT,
	`CREATED_AT` DATETIME,
	`UPDATED_BY` BIGINT,
	`UPDATED_AT` DATETIME,
	
	PRIMARY KEY (`ID`)
) DEFAULT CHARSET=UTF8;

ALTER TABLE FILE_ITEM
   ADD CONSTRAINT UX_FILE_ITEM UNIQUE (FILE_GROUP_KEY, PARAM_NAME, VERSION, POSITION);
ALTER TABLE FILE_ITEM
   ADD CONSTRAINT UX_FILE_ITEM2 UNIQUE (FILE_TYPE, FILE_NO, VERSION, POSITION);

COMMIT;