BEGIN;
ALTER TABLE `WORK_ORDER`
    ADD COLUMN REQUEST_CHANGE VARCHAR(1) DEFAULT NULL;
ALTER TABLE `WORK_ORDER`
    ADD COLUMN REQUEST_CHANGE_APPROVED VARCHAR(1) DEFAULT NULL;
ALTER TABLE `WORK_ORDER`
    ADD COLUMN ORIGINAL_ID BIGINT DEFAULT NULL;
COMMIT;