BEGIN;
DROP TABLE IF EXISTS `REJECT_RATE_CONFIGURATION`;
CREATE TABLE `REJECT_RATE_CONFIGURATION`
(
    `ID`         BIGINT NOT NULL,
    `CREATED_AT` DATETIME     DEFAULT NULL,
    `UPDATED_AT` DATETIME     DEFAULT NULL,
    `CREATED_BY` BIGINT       DEFAULT NULL,
    `UPDATED_BY` BIGINT       DEFAULT NULL,
    `FREQUENT`   VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

INSERT INTO `REJECT_RATE_CONFIGURATION` (ID, CREATED_AT, UPDATED_AT, FREQUENT) VALUES (1, NOW(), NOW(), 'DAILY');

ALTER TABLE PRODUCED_PART ADD COLUMN `HOUR` VARCHAR(255) DEFAULT NULL;
COMMIT;