DROP TABLE IF EXISTS PRODUCT_DEMAND;

CREATE TABLE PRODUCT_DEMAND (
	ID bigint not null auto_increment,
	
	PRODUCT_ID bigint,
	
	PERIOD_TYPE varchar(20),
	PERIOD_VALUE varchar(20),
	QUANTITY bigint,
	
	CREATED_BY bigint,
	CREATED_AT datetime,
	UPDATED_BY bigint,
	UPDATED_AT datetime,
	
	PRIMARY KEY (ID)
) CHARSET=utf8;

ALTER TABLE PRODUCT_DEMAND
	ADD CONSTRAINT FK_PRODUCT_DEMAND_PRODUCT
	FOREIGN KEY (PRODUCT_ID)
	REFERENCES CATEGORY (ID);

ALTER TABLE PRODUCT_DEMAND
	ADD CONSTRAINT UX_PRODUCT_DEMAND 
	UNIQUE (PRODUCT_ID, PERIOD_TYPE, PERIOD_VALUE);


DROP TABLE IF EXISTS PART_DEMAND;

CREATE TABLE PART_DEMAND (
	ID bigint not null auto_increment,
	
	PRODUCT_ID bigint,
	PART_ID bigint,
	
	PERIOD_TYPE varchar(20),
	PERIOD_VALUE varchar(20),
	QUANTITY bigint,
	
	CREATED_BY bigint,
	CREATED_AT datetime,
	UPDATED_BY bigint,
	UPDATED_AT datetime,
	
	PRIMARY KEY (ID)
) CHARSET=utf8;

ALTER TABLE PART_DEMAND
	ADD CONSTRAINT FK_PART_DEMAND_PRODUCT
	FOREIGN KEY (PRODUCT_ID)
	REFERENCES CATEGORY (ID);

ALTER TABLE PART_DEMAND
	ADD CONSTRAINT FK_PART_DEMAND_PART
	FOREIGN KEY (PART_ID)
	REFERENCES PART (ID);

ALTER TABLE PART_DEMAND
	ADD CONSTRAINT UX_PART_DEMAND
	UNIQUE (PRODUCT_ID, PART_ID, PERIOD_TYPE, PERIOD_VALUE);


DROP TABLE IF EXISTS PART_ORDER;

CREATE TABLE PART_ORDER (
	ID bigint not null auto_increment,
	
	PRODUCT_ID bigint,
	PART_ID bigint,
	SUPPLIER_ID bigint,
	
	PERIOD_TYPE varchar(20),
	PERIOD_VALUE varchar(20),
	QUANTITY bigint,
	
	CREATED_BY bigint,
	CREATED_AT datetime,
	UPDATED_BY bigint,
	UPDATED_AT datetime,
	
	PRIMARY KEY (ID)
) CHARSET=utf8;

ALTER TABLE PART_ORDER
	ADD CONSTRAINT FK_PART_ORDER_PRODUCT
	FOREIGN KEY (PRODUCT_ID)
	REFERENCES CATEGORY (ID);

ALTER TABLE PART_ORDER
	ADD CONSTRAINT FK_PART_ORDER_PART
	FOREIGN KEY (PART_ID)
	REFERENCES PART (ID);

ALTER TABLE PART_ORDER
	ADD CONSTRAINT FK_PART_ORDER_SUPPLIER
	FOREIGN KEY (SUPPLIER_ID)
	REFERENCES COMPANY (ID);

ALTER TABLE PART_ORDER
	ADD CONSTRAINT UX_PART_ORDER
	UNIQUE (PRODUCT_ID, PART_ID, SUPPLIER_ID, PERIOD_TYPE, PERIOD_VALUE);


DROP TABLE IF EXISTS PRODUCT_STAT;

CREATE TABLE PRODUCT_STAT (
	ID bigint not null auto_increment,
	
	PRODUCT_ID bigint,
	
	WEEK varchar(6),
	YEAR varchar(4),
	MONTH varchar(6),
	DAY varchar(8),
	
	PART_COUNT integer,
	SUPPLIER_COUNT integer,
	MOLD_COUNT integer,
	
	PRODUCED bigint,
	PRODUCED_VAL bigint,
	DAILY_CAPACITY bigint,
	
	CREATED_AT datetime,
	UPDATED_AT datetime,
	
	PRIMARY KEY (ID)
) CHARSET=utf8;

ALTER TABLE PRODUCT_STAT
	ADD CONSTRAINT FK_PRODUCT_STAT_PRODUCT
	FOREIGN KEY (PRODUCT_ID)
	REFERENCES CATEGORY (ID);

ALTER TABLE PRODUCT_STAT
	ADD CONSTRAINT UX_PRODUCT_STAT 
	UNIQUE (PRODUCT_ID, DAY);


DROP TABLE IF EXISTS PART_STAT;

CREATE TABLE PART_STAT (
	ID bigint not null auto_increment,
	
	PRODUCT_ID bigint,
	PART_ID bigint,
	SUPPLIER_ID bigint,
	MOLD_ID bigint,
	
	WEEK varchar(6),
	YEAR varchar(4),
	MONTH varchar(6),
	DAY varchar(8),
	
	PRODUCED bigint,
	PRODUCED_VAL bigint,
	DAILY_CAPACITY bigint,
	
	CREATED_AT datetime,
	UPDATED_AT datetime,
	
	PRIMARY KEY (ID)
) CHARSET=utf8;

ALTER TABLE PART_STAT
	ADD CONSTRAINT FK_PART_STAT_PART
	FOREIGN KEY (PART_ID)
	REFERENCES PART (ID);

ALTER TABLE PART_STAT
	ADD CONSTRAINT FK_PART_STAT_SUPPLIER
	FOREIGN KEY (SUPPLIER_ID)
	REFERENCES COMPANY (ID);

ALTER TABLE PART_STAT
	ADD CONSTRAINT FK_PART_STAT_MOLD
	FOREIGN KEY (MOLD_ID)
	REFERENCES MOLD (ID);

ALTER TABLE PART_STAT
	ADD CONSTRAINT UX_PART_STAT
	UNIQUE (PRODUCT_ID, PART_ID, SUPPLIER_ID, MOLD_ID, DAY);