DROP TABLE IF EXISTS SYNC_CTRL_DATA;

CREATE TABLE SYNC_CTRL_DATA (
	ID bigint not null auto_increment,
	
	NAME varchar(100),
	
	CREATED_BY bigint,
	CREATED_AT datetime,
	UPDATED_BY bigint,
	UPDATED_AT datetime,
	
	PRIMARY KEY (ID)
) CHARSET=utf8;

ALTER TABLE SYNC_CTRL_DATA
	ADD CONSTRAINT UX_SYNC_CTRL_DATA
	UNIQUE (NAME);