DROP TABLE IF EXISTS PRODUCT_STATISTICS;

CREATE TABLE PRODUCT_STATISTICS (
	ID bigint not null,
	
	PART_COUNT integer,
	MOLD_COUNT integer,
	SUPPLIER_COUNT integer,
	
	TOTAL_PRODUCED bigint,
	TOTAL_MAX_CAPACITY bigint,
	WEEKLY_MAX_CAPACITY bigint,
	TOTAL_PRODUCTION_DEMAND bigint,
	WEEKLY_PRODUCTION_DEMAND bigint,
	
	CREATED_AT datetime,
	UPDATED_AT datetime,
	
	PRIMARY KEY (ID)
) CHARSET=utf8;
