BEGIN;
DROP TABLE IF EXISTS IMPORT_FILE;
CREATE TABLE IMPORT_FILE
(
    ID            BIGINT NOT NULL AUTO_INCREMENT,
    FILENAME      VARCHAR(200),
    DATA_TYPE     VARCHAR(20),
    `STATUS`     VARCHAR(20),
    NEW_RECODE    BIGINT,
    UPDATE_RECODE BIGINT,
    ERROR_RECODE  BIGINT,
    UPLOAD_TIME   DATETIME,
    DONE_TIME   DATETIME,
    UPLOAD_BY     BIGINT,
    `CREATED_AT`  DATETIME DEFAULT NOW(),
    `UPDATED_AT`  DATETIME DEFAULT NOW(),
    PRIMARY KEY (ID)
) CHARSET = UTF8;
COMMIT;
