BEGIN;
ALTER TABLE CHECKLIST ADD COLUMN OBJECT_TYPE varchar(255);
UPDATE CHECKLIST SET OBJECT_TYPE = 'CHECK_LIST' WHERE OBJECT_TYPE IS NULL;

DROP TABLE IF EXISTS `WORK_ORDER_COST`;
DROP TABLE IF EXISTS `WORK_ORDER_USER`;
DROP TABLE IF EXISTS `WORK_ORDER_ASSET`;
DROP TABLE IF EXISTS `WORK_ORDER`;
CREATE TABLE `WORK_ORDER`
(
    `ID`                 BIGINT NOT NULL AUTO_INCREMENT,
    `WORK_ORDER_ID`      VARCHAR(255) DEFAULT NULL,
    `ORDER_TYPE`         VARCHAR(50)  DEFAULT NULL,
    `STATUS`             VARCHAR(20)  DEFAULT NULL,
    `DETAILS`            LONGTEXT     DEFAULT NULL,
    `PRIORITY`           VARCHAR(20)  DEFAULT NULL,
    `CHECKLIST_ID`       BIGINT       DEFAULT NULL,
    `CHECKLIST_ITEM_STR` LONGTEXT     DEFAULT NULL,
    `PICKLIST_ID`        BIGINT       DEFAULT NULL,
    `PICKLIST_ITEM_STR`  LONGTEXT     DEFAULT NULL,
    `COST`               VARCHAR(1)   DEFAULT 'N',
    `PICKING_LIST`       VARCHAR(1)   DEFAULT 'N',
    `START`              DATETIME     DEFAULT NULL,
    `END`                DATETIME     DEFAULT NULL,
    `STARTED_ON`         DATETIME     DEFAULT NULL,
    `COMPLETED_ON`       DATETIME     DEFAULT NULL,
    `FREQUENT`           VARCHAR(20)  DEFAULT NULL,
    `REPEAT_ON`          VARCHAR(20)  DEFAULT NULL,
    `END_AFTER`          INT     DEFAULT NULL,
    `CREATED_AT`         DATETIME     DEFAULT NULL,
    `UPDATED_AT`         DATETIME     DEFAULT NULL,
    `CREATED_BY`         BIGINT       DEFAULT NULL,
    `UPDATED_BY`         BIGINT       DEFAULT NULL,
    `FAILURE_TIME`       DATETIME     DEFAULT NULL,
    `NUMBER_OF_BACKUPS`  INT          DEFAULT NULL,
    `COST_ESTIMATE`      DOUBLE       DEFAULT NULL,
    `COST_DETAILS`       LONGTEXT     DEFAULT NULL,
    `CM_REQUESTED`       VARCHAR(1)   DEFAULT NULL,
    `APPROVED`           VARCHAR(1)   DEFAULT NULL,
    `NOTE`               LONGTEXT   DEFAULT NULL,
    PRIMARY KEY (`ID`),
    KEY `IDX_WORK_ORDER_ID` (`WORK_ORDER_ID`),
    KEY `FKa0obeytuj7jp71l4c5r1askek8s` (`CHECKLIST_ID`),
    CONSTRAINT `FKa0obeytuj7jp71l4c5r1askek8s` FOREIGN KEY (`CHECKLIST_ID`) REFERENCES `CHECKLIST` (`ID`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1;


CREATE TABLE `WORK_ORDER_ASSET`
(
    `ID`            BIGINT NOT NULL AUTO_INCREMENT,
    `WORK_ORDER_ID` BIGINT       DEFAULT NULL,
    `ASSET_ID`      BIGINT       DEFAULT NULL,
    `ASSET_CODE`    VARCHAR(255) DEFAULT NULL,
    `TYPE`          VARCHAR(20)  DEFAULT NULL,
    `CREATED_AT`    DATETIME     DEFAULT NULL,
    `UPDATED_AT`    DATETIME     DEFAULT NULL,
    PRIMARY KEY (`ID`),
    KEY `FKa0obeytafgagasdw1askek8s` (`WORK_ORDER_ID`),
    CONSTRAINT `FKa0obeytafgagasdw1askek8s` FOREIGN KEY (`WORK_ORDER_ID`) REFERENCES `WORK_ORDER` (`ID`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1;


CREATE TABLE `WORK_ORDER_USER`
(
    `ID`            BIGINT NOT NULL AUTO_INCREMENT,
    `WORK_ORDER_ID` BIGINT   DEFAULT NULL,
    `USER_ID`       BIGINT   DEFAULT NULL,
    `CREATED_AT`    DATETIME DEFAULT NULL,
    `UPDATED_AT`    DATETIME DEFAULT NULL,
    PRIMARY KEY (`ID`),
    KEY `FKa0obeyhhtyryrskek8s` (`WORK_ORDER_ID`),
    CONSTRAINT `FKa0obeyhhtyryrskek8s` FOREIGN KEY (`WORK_ORDER_ID`) REFERENCES `WORK_ORDER` (`ID`),
    KEY `FKa0obeythgjertqedkek8s` (`USER_ID`),
    CONSTRAINT `FKa0obeythgjertqedkek8s` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1;


CREATE TABLE `WORK_ORDER_COST`
(
    `ID`            BIGINT NOT NULL AUTO_INCREMENT,
    `WORK_ORDER_ID` BIGINT   DEFAULT NULL,
    `COST`     DOUBLE       DEFAULT NULL,
    `DETAILS`      LONGTEXT     DEFAULT NULL,
    `CREATED_AT`    DATETIME DEFAULT NULL,
    `UPDATED_AT`    DATETIME DEFAULT NULL,
    PRIMARY KEY (`ID`),
    KEY `FKa0obeyhahaertetek8s` (`WORK_ORDER_ID`),
    CONSTRAINT `FKa0obeyhahaertetek8s` FOREIGN KEY (`WORK_ORDER_ID`) REFERENCES `WORK_ORDER` (`ID`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1;

COMMIT;