BEGIN;
ALTER TABLE `MOLD` ADD COLUMN SALVAGE_VALUE DOUBLE DEFAULT NULL;
ALTER TABLE `MOLD` ADD COLUMN SALVAGE_CURRENCY VARCHAR(255) DEFAULT NULL;
ALTER TABLE `MOLD` ADD COLUMN PO_NUMBER VARCHAR(255) DEFAULT NULL;
ALTER TABLE `MOLD` ADD COLUMN PO_DATE DATETIME DEFAULT NULL;
COMMIT;