alter table DATA_COUNTER add COLUMN `READ_TIME` VARCHAR(23) NULL DEFAULT NULL COLLATE 'utf8_general_ci' ;
alter table DATA_ACCELERATION add COLUMN `READ_TIME` VARCHAR(23) NULL DEFAULT NULL COLLATE 'utf8_general_ci' ;
alter table DATA add COLUMN `READ_TIME` VARCHAR(23) NULL DEFAULT NULL COLLATE 'utf8_general_ci' ;
alter table DATA  add COLUMN `DUPLICATE_COUNT` INT(10) NOT NULL;
