BEGIN;
CREATE TABLE `CHECKLIST_USER`
(
    `ID`            BIGINT NOT NULL AUTO_INCREMENT,
    `CHECKLIST_ID` BIGINT   DEFAULT NULL,
    `USER_ID`       BIGINT   DEFAULT NULL,
    `CREATED_AT`    DATETIME DEFAULT NULL,
    `UPDATED_AT`    DATETIME DEFAULT NULL,
    PRIMARY KEY (`ID`),
    KEY `FKa0obeyhhtyryagasgarskek8s` (`CHECKLIST_ID`),
    CONSTRAINT `FKa0obeyhhtyryagasgarskek8s` FOREIGN KEY (`CHECKLIST_ID`) REFERENCES `CHECKLIST` (`ID`),
    KEY `FKa0obeythgjert36346qedkek8s` (`USER_ID`),
    CONSTRAINT `FKa0obeythgjert36346qedkek8s` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE = INNODB
  AUTO_INCREMENT = 1 DEFAULT CHARSET=utf8mb4;
COMMIT;