ALTER TABLE `MOLD`
	CHANGE COLUMN `EQUIPMENT_CODE` `EQUIPMENT_CODE` varchar(255) AFTER `ID`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `SUPPLIER_COMPANY_ID` `SUPPLIER_COMPANY_ID` bigint AFTER `EQUIPMENT_CODE`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `TOOL_MAKER_COMPANY_ID` `TOOL_MAKER_COMPANY_ID` bigint AFTER `SUPPLIER_COMPANY_ID`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `COMPANY_ID` `COMPANY_ID` bigint AFTER `TOOL_MAKER_COMPANY_ID`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `LOCATION_ID` `LOCATION_ID` bigint AFTER `COMPANY_ID`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `AREA_ID` `AREA_ID` bigint AFTER `LOCATION_ID`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `LOCATION_CHANGED` `LOCATION_CHANGED` varchar(1) default 'N' AFTER `AREA_ID`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `MACHINE_ID` `MACHINE_ID` bigint AFTER `LOCATION_CHANGED`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `COUNTER_ID` `COUNTER_ID` bigint AFTER `MACHINE_ID`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `TOOLING_STATUS` `TOOLING_STATUS` varchar(20) AFTER `COUNTER_ID`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `EQUIPMENT_STATUS` `EQUIPMENT_STATUS` varchar(20) AFTER `TOOLING_STATUS`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `OPERATING_STATUS` `OPERATING_STATUS` varchar(20) AFTER `EQUIPMENT_STATUS`;

ALTER TABLE `MOLD`
	ADD COLUMN `ENABLED` varchar(1) default 'Y' AFTER `OPERATING_STATUS`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `DELETED` `DELETED` varchar(1) default 'N' AFTER `ENABLED`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `UTILIZATION_RATE` `UTILIZATION_RATE` double AFTER `DELETED`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `PURCHASED_AT` `PURCHASED_AT` varchar(255) AFTER `UTILIZATION_RATE`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `INSTALLED_BY` `INSTALLED_BY` varchar(255) AFTER `PURCHASED_AT`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `INSTALLED_AT` `INSTALLED_AT` varchar(255) AFTER `INSTALLED_BY`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `ACTIVATED_AT` `ACTIVATED_AT` datetime AFTER `INSTALLED_AT`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `OPERATED_START_AT` `OPERATED_START_AT` datetime AFTER `ACTIVATED_AT`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `OPERATED_AT` `OPERATED_AT` datetime AFTER `OPERATED_START_AT`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `CONTRACTED_CYCLE_TIME` `CONTRACTED_CYCLE_TIME` integer AFTER `OPERATED_AT`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `TOOLMAKER_CONTRACTED_CYCLE_TIME` `TOOLMAKER_CONTRACTED_CYCLE_TIME` integer AFTER `CONTRACTED_CYCLE_TIME`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `WEIGHTED_AVERAGE_CYCLE_TIME` `WEIGHTED_AVERAGE_CYCLE_TIME` double AFTER `TOOLMAKER_CONTRACTED_CYCLE_TIME`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `LAST_CYCLE_TIME` `LAST_CYCLE_TIME` double AFTER `WEIGHTED_AVERAGE_CYCLE_TIME`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `DESIGNED_SHOT` `DESIGNED_SHOT` integer AFTER `LAST_CYCLE_TIME`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `LAST_SHOT` `LAST_SHOT` integer AFTER `DESIGNED_SHOT`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `LAST_SHOT_AT` `LAST_SHOT_AT` datetime AFTER `LAST_SHOT`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `LAST_SHOT_AT_VAL` `LAST_SHOT_AT_VAL` datetime AFTER `LAST_SHOT_AT`;

ALTER TABLE `MOLD`
	CHANGE COLUMN `LAST_SHOT_MADE_AT` `LAST_SHOT_MADE_AT` datetime AFTER `LAST_SHOT_AT_VAL`;