BEGIN;

DELETE
FROM `WORK_ORDER_USER`
WHERE `WORK_ORDER_ID` IN (SELECT `ID` FROM `WORK_ORDER` WHERE `STATUS` = 'CHANGE_REQUESTED' AND `REQUEST_CHANGE` = 'Y');

DELETE
FROM `WORK_ORDER_ASSET`
WHERE `WORK_ORDER_ID` IN (SELECT `ID` FROM `WORK_ORDER` WHERE `STATUS` = 'CHANGE_REQUESTED' AND `REQUEST_CHANGE` = 'Y');

DELETE
FROM `WORK_ORDER_COST`
WHERE `WORK_ORDER_ID` IN (SELECT `ID` FROM `WORK_ORDER` WHERE `STATUS` = 'CHANGE_REQUESTED' AND `REQUEST_CHANGE` = 'Y');

DELETE
FROM `WORK_ORDER`
WHERE `STATUS` = 'CHANGE_REQUESTED' AND `REQUEST_CHANGE` = 'Y';

COMMIT;