DROP TABLE IF EXISTS `LOGIN_HIST`;

CREATE TABLE `LOGIN_HIST` (
	`SESSION_ID` varchar(100),
	`USER_ID` bigint,
	`CLIENT_TYPE` varchar(20),
	`CLIENT_ID` varchar(100),
	`LOGIN_AT` datetime,
	`LOGOUT_AT` datetime,
	`EXPIRED_AT` datetime,
	`MESSAGING_TOKEN` varchar(255),
	`CREATED_BY` bigint,
	`CREATED_AT` datetime,
	`UPDATED_BY` bigint,
	`UPDATED_AT` datetime,
	PRIMARY KEY (`SESSION_ID`)
) DEFAULT CHARSET=UTF8;

ALTER TABLE `LOGIN_HIST`
	ADD INDEX IX_LOGIN_HIST_01 (`USER_ID`, `EXPIRED_AT`);

ALTER TABLE `LOGIN_HIST`
	ADD INDEX IX_LOGIN_HIST_02 (`CLIENT_ID`, `LOGIN_AT`);

ALTER TABLE `LOGIN_HIST`
	ADD INDEX IX_LOGIN_HIST_03 (`MESSAGING_TOKEN`);