DROP TABLE IF EXISTS `MOLD_PLANT_ENGINEER`;

CREATE TABLE `MOLD_PLANT_ENGINEER`
(
	`MOLD_ID` bigint not null,
	`USER_ID` bigint not null,
	PRIMARY KEY (`MOLD_ID`, `USER_ID`),
	CONSTRAINT `FK_MOLD_PLANT_ENGINEER__USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`),
	CONSTRAINT `FK_MOLD_PLANT_ENGINEER__MOLD_ID` FOREIGN KEY (`MOLD_ID`) REFERENCES `MOLD` (`ID`)
);
