ALTER TABLE `CATEGORY_VERSION`
	ADD COLUMN `CREATED_BY` bigint AFTER `CREATED_AT`;

ALTER TABLE `CHECKLIST_VERSION`
	ADD COLUMN `CREATED_BY` bigint AFTER `CREATED_AT`;

ALTER TABLE `COMPANY_VERSION`
	ADD COLUMN `CREATED_BY` bigint AFTER `CREATED_AT`;

ALTER TABLE `COUNTER_VERSION`
	ADD COLUMN `CREATED_BY` bigint AFTER `CREATED_AT`;

ALTER TABLE `LOCATION_VERSION`
	ADD COLUMN `CREATED_BY` bigint AFTER `CREATED_AT`;

ALTER TABLE `MACHINE_VERSION`
	ADD COLUMN `CREATED_BY` bigint AFTER `CREATED_AT`;

ALTER TABLE `MOLD_VERSION`
	ADD COLUMN `CREATED_BY` bigint AFTER `CREATED_AT`;

ALTER TABLE `PART_VERSION`
	ADD COLUMN `CREATED_BY` bigint AFTER `CREATED_AT`;

ALTER TABLE `REVISION_HISTORY`
	ADD COLUMN `CREATED_BY` bigint AFTER `CREATED_AT`;

ALTER TABLE `ROLE_VERSION`
	ADD COLUMN `CREATED_BY` bigint AFTER `CREATED_AT`;

ALTER TABLE `TERMINAL_VERSION`
	ADD COLUMN `CREATED_BY` bigint AFTER `CREATED_AT`;

ALTER TABLE `USER_VERSION`
	ADD COLUMN `CREATED_BY` bigint AFTER `CREATED_AT`;