BEGIN;

ALTER TABLE `MOLD_LOCATION`
	ADD CONSTRAINT `FK_MOLD_LOCATION__PREVIOUS_LOCATION_ID`
		FOREIGN KEY (`PREVIOUS_LOCATION_ID`) REFERENCES `LOCATION`(`ID`);

ALTER TABLE `MOLD_LOCATION`
	ADD COLUMN `PREVIOUS_AREA_ID` bigint AFTER `PREVIOUS_LOCATION_ID`;
ALTER TABLE `MOLD_LOCATION`
	ADD CONSTRAINT `FK_MOLD_LOCATION__PREVIOUS_AREA_ID`
		FOREIGN KEY (`PREVIOUS_AREA_ID`) REFERENCES `AREA`(`ID`);

COMMIT;