BEGIN;

DELETE FROM DATABASECHANGELOG WHERE ID ='2023011615-2';

UPDATE SYSTEM_NOTE SET SYSTEM_NOTE_FUNCTION = 'CATEGORY' WHERE SYSTEM_NOTE_FUNCTION = 'CATEGORY_SETTING';
UPDATE SYSTEM_NOTE SET SYSTEM_NOTE_FUNCTION = 'COMPANY' WHERE SYSTEM_NOTE_FUNCTION = 'COMPANY_SETTING';
UPDATE SYSTEM_NOTE SET SYSTEM_NOTE_FUNCTION = 'COUNTER' WHERE SYSTEM_NOTE_FUNCTION = 'COUNTER_SETTING';
UPDATE SYSTEM_NOTE SET SYSTEM_NOTE_FUNCTION = 'PART' WHERE SYSTEM_NOTE_FUNCTION = 'PART_DASHBOARD';
UPDATE SYSTEM_NOTE SET SYSTEM_NOTE_FUNCTION = 'PART_SETTINGS' WHERE SYSTEM_NOTE_FUNCTION = 'PART_SETTING';
UPDATE SYSTEM_NOTE SET SYSTEM_NOTE_FUNCTION = 'TERMINAL' WHERE SYSTEM_NOTE_FUNCTION = 'TERMINAL_SETTING';
UPDATE SYSTEM_NOTE SET SYSTEM_NOTE_FUNCTION = 'TOOLING' WHERE SYSTEM_NOTE_FUNCTION = 'TOOLING_DASHBOARD';
UPDATE SYSTEM_NOTE SET SYSTEM_NOTE_FUNCTION = 'TOOLING_SETTINGS' WHERE SYSTEM_NOTE_FUNCTION = 'TOOLING_SETTING';
UPDATE SYSTEM_NOTE SET SYSTEM_NOTE_FUNCTION = 'UPTIME_ALERT' WHERE SYSTEM_NOTE_FUNCTION = 'EFFICIENCY_ALERT';
UPDATE SYSTEM_NOTE SET SYSTEM_NOTE_FUNCTION = 'DETACHMENT' WHERE SYSTEM_NOTE_FUNCTION = 'DETACHMENT_ALERT';

UPDATE BROADCAST_NOTIFICATION SET SYSTEM_FUNCTION = 'CATEGORY' WHERE SYSTEM_FUNCTION = 'CATEGORY_SETTING';
UPDATE BROADCAST_NOTIFICATION SET SYSTEM_FUNCTION = 'COMPANY' WHERE SYSTEM_FUNCTION = 'COMPANY_SETTING';
UPDATE BROADCAST_NOTIFICATION SET SYSTEM_FUNCTION = 'COUNTER' WHERE SYSTEM_FUNCTION = 'COUNTER_SETTING';
UPDATE BROADCAST_NOTIFICATION SET SYSTEM_FUNCTION = 'PART' WHERE SYSTEM_FUNCTION = 'PART_DASHBOARD';
UPDATE BROADCAST_NOTIFICATION SET SYSTEM_FUNCTION = 'PART_SETTINGS' WHERE SYSTEM_FUNCTION = 'PART_SETTING';
UPDATE BROADCAST_NOTIFICATION SET SYSTEM_FUNCTION = 'TERMINAL' WHERE SYSTEM_FUNCTION = 'TERMINAL_SETTING';
UPDATE BROADCAST_NOTIFICATION SET SYSTEM_FUNCTION = 'TOOLING' WHERE SYSTEM_FUNCTION = 'TOOLING_DASHBOARD';
UPDATE BROADCAST_NOTIFICATION SET SYSTEM_FUNCTION = 'TOOLING_SETTINGS' WHERE SYSTEM_FUNCTION = 'TOOLING_SETTING';
UPDATE BROADCAST_NOTIFICATION SET SYSTEM_FUNCTION = 'UPTIME_ALERT' WHERE SYSTEM_FUNCTION = 'EFFICIENCY_ALERT';
UPDATE BROADCAST_NOTIFICATION SET SYSTEM_FUNCTION = 'DETACHMENT' WHERE SYSTEM_FUNCTION = 'DETACHMENT_ALERT';

UPDATE NOTIFICATION SET SYSTEM_NOTE_FUNCTION = 'CATEGORY' WHERE SYSTEM_NOTE_FUNCTION = 'CATEGORY_SETTING';
UPDATE NOTIFICATION SET SYSTEM_NOTE_FUNCTION = 'COMPANY' WHERE SYSTEM_NOTE_FUNCTION = 'COMPANY_SETTING';
UPDATE NOTIFICATION SET SYSTEM_NOTE_FUNCTION = 'COUNTER' WHERE SYSTEM_NOTE_FUNCTION = 'COUNTER_SETTING';
UPDATE NOTIFICATION SET SYSTEM_NOTE_FUNCTION = 'PART' WHERE SYSTEM_NOTE_FUNCTION = 'PART_DASHBOARD';
UPDATE NOTIFICATION SET SYSTEM_NOTE_FUNCTION = 'PART_SETTINGS' WHERE SYSTEM_NOTE_FUNCTION = 'PART_SETTING';
UPDATE NOTIFICATION SET SYSTEM_NOTE_FUNCTION = 'TERMINAL' WHERE SYSTEM_NOTE_FUNCTION = 'TERMINAL_SETTING';
UPDATE NOTIFICATION SET SYSTEM_NOTE_FUNCTION = 'TOOLING' WHERE SYSTEM_NOTE_FUNCTION = 'TOOLING_DASHBOARD';
UPDATE NOTIFICATION SET SYSTEM_NOTE_FUNCTION = 'TOOLING_SETTINGS' WHERE SYSTEM_NOTE_FUNCTION = 'TOOLING_SETTING';
UPDATE NOTIFICATION SET SYSTEM_NOTE_FUNCTION = 'UPTIME_ALERT' WHERE SYSTEM_NOTE_FUNCTION = 'EFFICIENCY_ALERT';
UPDATE NOTIFICATION SET SYSTEM_NOTE_FUNCTION = 'DETACHMENT' WHERE SYSTEM_NOTE_FUNCTION = 'DETACHMENT_ALERT';

UPDATE TOPIC SET SYSTEM_NOTE_FUNCTION = 'CATEGORY' WHERE SYSTEM_NOTE_FUNCTION = 'CATEGORY_SETTING';
UPDATE TOPIC SET SYSTEM_NOTE_FUNCTION = 'COMPANY' WHERE SYSTEM_NOTE_FUNCTION = 'COMPANY_SETTING';
UPDATE TOPIC SET SYSTEM_NOTE_FUNCTION = 'COUNTER' WHERE SYSTEM_NOTE_FUNCTION = 'COUNTER_SETTING';
UPDATE TOPIC SET SYSTEM_NOTE_FUNCTION = 'PART' WHERE SYSTEM_NOTE_FUNCTION = 'PART_DASHBOARD';
UPDATE TOPIC SET SYSTEM_NOTE_FUNCTION = 'PART_SETTINGS' WHERE SYSTEM_NOTE_FUNCTION = 'PART_SETTING';
UPDATE TOPIC SET SYSTEM_NOTE_FUNCTION = 'TERMINAL' WHERE SYSTEM_NOTE_FUNCTION = 'TERMINAL_SETTING';
UPDATE TOPIC SET SYSTEM_NOTE_FUNCTION = 'TOOLING' WHERE SYSTEM_NOTE_FUNCTION = 'TOOLING_DASHBOARD';
UPDATE TOPIC SET SYSTEM_NOTE_FUNCTION = 'TOOLING_SETTINGS' WHERE SYSTEM_NOTE_FUNCTION = 'TOOLING_SETTING';
UPDATE TOPIC SET SYSTEM_NOTE_FUNCTION = 'UPTIME_ALERT' WHERE SYSTEM_NOTE_FUNCTION = 'EFFICIENCY_ALERT';
UPDATE TOPIC SET SYSTEM_NOTE_FUNCTION = 'DETACHMENT' WHERE SYSTEM_NOTE_FUNCTION = 'DETACHMENT_ALERT';

COMMIT ;
