BEGIN;
UPDATE `MOLD_LOCATION` SET MOLD_LOCATION_STATUS = 'PENDING' WHERE MOLD_LOCATION_STATUS = 'CHANGED';
UPDATE `MOLD_LOCATION` SET MOLD_LOCATION_STATUS = 'APPROVED' WHERE MOLD_LOCATION_STATUS = 'AUTHORIZED';
UPDATE `MOLD_LOCATION` SET MOLD_LOCATION_STATUS = 'UNAPPROVED' WHERE MOLD_LOCATION_STATUS = 'UNAUTHORIZED';
COMMIT;