BEGIN;

ALTER TABLE `PART_STAT`
	ADD COLUMN `LOCATION_ID` bigint AFTER `SUPPLIER_ID`;
ALTER TABLE `PART_STAT`
	ADD CONSTRAINT `FK_PART_STAT__LOCATION_ID`
		FOREIGN KEY (`LOCATION_ID`) REFERENCES `LOCATION`(`ID`);

ALTER TABLE `PART_STAT`
	DROP INDEX `UX_PART_STAT`;

ALTER TABLE `PART_STAT`
	ADD CONSTRAINT `UX_PART_STAT`
	UNIQUE (`PRODUCT_ID`, `PART_ID`, `SUPPLIER_ID`, `LOCATION_ID`, `MOLD_ID`, `DAY`);

COMMIT;