BEGIN;
UPDATE `MOLD_LOCATION` SET MOLD_LOCATION_STATUS = 'PENDING' WHERE MOLD_LOCATION_STATUS = 'CHANGED';
UPDATE `MOLD_LOCATION` SET MOLD_LOCATION_STATUS = 'AUTHORIZED' WHERE MOLD_LOCATION_STATUS = 'CONFIRMED';
COMMIT;