
ALTER TABLE `COUNTER`
	ADD COLUMN `LAST_TERMINAL_ID` bigint AFTER `LAST_SHOT_AT`;

ALTER TABLE `COUNTER`
	ADD CONSTRAINT `FK_COUNTER__LAST_TERMINAL_ID`
		FOREIGN KEY (`LAST_TERMINAL_ID`) REFERENCES `TERMINAL`(`ID`);
