ALTER TABLE `CYCLE_TIME_DEVIATION`
	ADD INDEX `IX_CTD__SUPPLIER_ID` (`SUPPLIER_ID`),
	ADD INDEX `IX_CTD__MOLD_ID` (`MOLD_ID`),
	ADD INDEX `IX_CTD__PART_ID` (`PART_ID`),
	ADD INDEX `IX_CTD__YEAR` (`YEAR`),
	ADD INDEX `IX_CTD__MONTH` (`MONTH`),
	ADD INDEX `IX_CTD__WEEK` (`WEEK`),
	ADD INDEX `IX_CTD__DAY` (`DAY`);