ALTER TABLE `LOCATION`
	CHANGE COLUMN `NAME` `NAME` varchar(255) AFTER `ID`;

ALTER TABLE `LOCATION`
	CHANGE COLUMN `LOCATION_CODE` `LOCATION_CODE` varchar(20) AFTER `NAME`;

ALTER TABLE `LOCATION`
	CHANGE COLUMN `COMPANY_ID` `COMPANY_ID` bigint AFTER `LOCATION_CODE`;

ALTER TABLE `LOCATION`
	CHANGE COLUMN `ENABLED` `ENABLED` varchar(1) AFTER `COMPANY_ID`;

ALTER TABLE `LOCATION`
	CHANGE COLUMN `ADDRESS` `ADDRESS` varchar(500) AFTER `ENABLED`;

ALTER TABLE `LOCATION`
	CHANGE COLUMN `LATITUDE` `LATITUDE` double AFTER `ADDRESS`;

ALTER TABLE `LOCATION`
	CHANGE COLUMN `LONGITUDE` `LONGITUDE` double AFTER `LATITUDE`;

ALTER TABLE `LOCATION`
	CHANGE COLUMN `TIME_ZONE_ID` `TIME_ZONE_ID` varchar(20) AFTER `LONGITUDE`;

ALTER TABLE `LOCATION`
	CHANGE COLUMN `MEMO` `MEMO` longtext AFTER `TIME_ZONE_ID`;

ALTER TABLE `MOLD_LOCATION`
	CHANGE COLUMN `MOLD_ID` `MOLD_ID` bigint AFTER `ID`;

ALTER TABLE `MOLD_LOCATION`
	CHANGE COLUMN `LOCATION_ID` `LOCATION_ID` bigint AFTER `MOLD_ID`;

ALTER TABLE `MOLD_LOCATION`
	CHANGE COLUMN `AREA_ID` `AREA_ID` bigint AFTER `LOCATION_ID`;

ALTER TABLE `MOLD_LOCATION`
	CHANGE COLUMN `PREVIOUS_LOCATION_ID` `PREVIOUS_LOCATION_ID` bigint AFTER `AREA_ID`;

ALTER TABLE `MOLD_LOCATION`
	CHANGE COLUMN `PREVIOUS_AREA_ID` `PREVIOUS_AREA_ID` bigint AFTER `PREVIOUS_LOCATION_ID`;

ALTER TABLE `MOLD_LOCATION`
	CHANGE COLUMN `MOLD_LOCATION_STATUS` `MOLD_LOCATION_STATUS` varchar(20) AFTER `PREVIOUS_AREA_ID`;

ALTER TABLE `MOLD_LOCATION`
	CHANGE COLUMN `NOTIFICATION_AT` `NOTIFICATION_AT` datetime AFTER `MOLD_LOCATION_STATUS`;

ALTER TABLE `MOLD_LOCATION`
	CHANGE COLUMN `CONFIRMED_BY` `CONFIRMED_BY` varchar(255) AFTER `NOTIFICATION_AT`;

ALTER TABLE `MOLD_LOCATION`
	CHANGE COLUMN `CONFIRMED_AT` `CONFIRMED_AT` datetime AFTER `CONFIRMED_BY`;

ALTER TABLE `MOLD_LOCATION`
	CHANGE COLUMN `MESSAGE` `MESSAGE` longtext AFTER `CONFIRMED_AT`;

ALTER TABLE `MOLD_LOCATION`
	ADD COLUMN `RELOCATION_TYPE` varchar(20) AFTER `MOLD_ID`;