
ALTER TABLE `MOLD_VERSION` 
	MODIFY COLUMN PARTS LONGTEXT;

ALTER TABLE `MOLD_VERSION` 
	MODIFY COLUMN PARTS_NAME LONGTEXT;

ALTER TABLE `MOLD_VERSION` 
	MODIFY COLUMN ENGINEER_IDS LONGTEXT;

ALTER TABLE `MOLD_VERSION` 
	MODIFY COLUMN ENGINEER_NAMES LONGTEXT;
