DROP TABLE IF EXISTS `PROD_MOLD_STAT`;

CREATE TABLE `PROD_MOLD_STAT` (
	`ID` bigint not null auto_increment,
	`MOLD_ID` bigint,
	`PRODUCT_ID` bigint,
	`PART_ID` bigint,
	`SUPPLIER_ID` bigint,
	`WEEK` varchar(6),
	`APPR_CYCLE_TIME` integer,
	`WEIGHTED_AVG_CYCLE_TIME` double,
	`IDEAL_SHOT_COUNT` bigint,
	`RECENT_SHOT_COUNT` bigint,
	`ACTUAL_SHOT_COUNT` bigint,
	`AVG_CYCLE_TIME` double,
	`PROD_HOURS_PER_DAY` integer,
	`PROD_DAYS` integer,
	`TARGET_UPTIME_RATE` integer,
	`CAVITY_COUNT` integer,
	`WEEKLY_CAPA` bigint,
	`CREATED_BY` bigint,
	`CREATED_AT` datetime,
	`UPDATED_BY` bigint,
	`UPDATED_AT` datetime,
	PRIMARY KEY (`ID`)
) DEFAULT CHARSET=UTF8;

ALTER TABLE `PROD_MOLD_STAT`
	ADD CONSTRAINT `UX_PROD_MOLD_STAT` UNIQUE (`MOLD_ID`, `PRODUCT_ID`, `PART_ID`, `SUPPLIER_ID`, `WEEK`);
ALTER TABLE `PROD_MOLD_STAT`
	ADD CONSTRAINT `FK_PROD_MOLD_STAT__MOLD_ID`
		FOREIGN KEY (`MOLD_ID`) REFERENCES `MOLD`(`ID`);
ALTER TABLE `PROD_MOLD_STAT`
	ADD CONSTRAINT `FK_PROD_MOLD_STAT__PRODUCT_ID`
		FOREIGN KEY (`PRODUCT_ID`) REFERENCES `CATEGORY`(`ID`);
ALTER TABLE `PROD_MOLD_STAT`
	ADD CONSTRAINT `FK_PROD_MOLD_STAT__PART_ID`
		FOREIGN KEY (`PART_ID`) REFERENCES `PART`(`ID`);
ALTER TABLE `PROD_MOLD_STAT`
	ADD CONSTRAINT `FK_PROD_MOLD_STAT__SUPPLIER_ID`
		FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `COMPANY`(`ID`);
