BEGIN;

ALTER TABLE `OPTION_FIELD_VALUE`
	ADD COLUMN `USER_ID` bigint;

ALTER TABLE `OPTION_FIELD_VALUE`
	DROP INDEX `UX_OPTION_FIELD_VALUE`;

ALTER TABLE `OPTION_FIELD_VALUE`
	ADD CONSTRAINT `UX_OPTION_FIELD_VALUE` UNIQUE (CONFIG_CATEGORY, USER_ID, FIELD_NAME);

COMMIT;