DROP TABLE IF EXISTS `MOLD_PROC_CHG`;

CREATE TABLE `MOLD_PROC_CHG` (
	`ID` bigint not null auto_increment,
	`MOLD_ID` bigint,
	`PROC_CHG_TIME` varchar(14),
	`YEAR` varchar(4),
	`MONTH` varchar(6),
	`WEEK` varchar(6),
	`DAY` varchar(8),
	`HOUR` varchar(10),
	`CREATED_AT` datetime,
	`UPDATED_AT` datetime,
	PRIMARY KEY (`ID`)
) DEFAULT CHARSET=UTF8;
	
CREATE INDEX IX_MOLD_PROC_CHG_01 ON MOLD_PROC_CHG (
	`YEAR`, `MOLD_ID`
);
	
CREATE INDEX IX_MOLD_PROC_CHG_02 ON MOLD_PROC_CHG (
	`MONTH`, `MOLD_ID`
);
	
CREATE INDEX IX_MOLD_PROC_CHG_03 ON MOLD_PROC_CHG (
	`WEEK`, `MOLD_ID`
);
	
CREATE INDEX IX_MOLD_PROC_CHG_04 ON MOLD_PROC_CHG (
	`DAY`, `MOLD_ID`
);
	
CREATE INDEX IX_MOLD_PROC_CHG_05 ON MOLD_PROC_CHG (
	`HOUR`, `MOLD_ID`
);