BEGIN;

DROP TABLE IF EXISTS `AREA`;

CREATE TABLE `AREA` (
	`ID` bigint not null auto_increment,
	`NAME` varchar(100),
	`AREA_TYPE` varchar(20),
	`POSITION` integer,
	`LOCATION_ID` bigint,
	`CREATED_BY` bigint,
	`CREATED_AT` datetime,
	`UPDATED_BY` bigint,
	`UPDATED_AT` datetime,
	PRIMARY KEY (`ID`)
) DEFAULT CHARSET=UTF8;

ALTER TABLE `AREA`
	ADD CONSTRAINT `UK_AREA` UNIQUE (`LOCATION_ID`, `NAME`);
ALTER TABLE `AREA`
	ADD CONSTRAINT `FK_AREA__LOCATION_ID`
		FOREIGN KEY (`LOCATION_ID`) REFERENCES `LOCATION`(`ID`);

ALTER TABLE `MOLD`
	ADD COLUMN `AREA_ID` bigint AFTER `LOCATION_ID`;
ALTER TABLE `MOLD`
	ADD CONSTRAINT `FK_MOLD__AREA_ID`
		FOREIGN KEY (`AREA_ID`) REFERENCES `AREA`(`ID`);

ALTER TABLE `TERMINAL`
	ADD COLUMN `AREA_ID` bigint AFTER `LOCATION_ID`;
ALTER TABLE `TERMINAL`
	ADD CONSTRAINT `FK_TERMINAL__AREA_ID`
		FOREIGN KEY (`AREA_ID`) REFERENCES `AREA`(`ID`);

ALTER TABLE `COUNTER`
	ADD COLUMN `AREA_ID` bigint AFTER `LOCATION_ID`;
ALTER TABLE `COUNTER`
	ADD CONSTRAINT `FK_COUNTER__AREA_ID`
		FOREIGN KEY (`AREA_ID`) REFERENCES `AREA`(`ID`);

COMMIT;