BEGIN;

ALTER TABLE `MOLD_LOCATION`
	ADD COLUMN `AREA_ID` bigint AFTER `LOCATION_ID`;
ALTER TABLE `MOLD_LOCATION`
	ADD CONSTRAINT `FK_MOLD_LOCATION__AREA_ID`
		FOREIGN KEY (`AREA_ID`) REFERENCES `AREA`(`ID`);

COMMIT;