DROP TABLE IF EXISTS `TRANSFER_INDEX`;

CREATE TABLE `TRANSFER_INDEX` (
	`ID` BIGINT not null auto_increment,
	`CI` varchar(100),
	`TFF` varchar(100),
	`CREATED_AT` datetime,
	PRIMARY KEY (ID)
);

ALTER TABLE `TRANSFER_INDEX`
   ADD CONSTRAINT `UX_TRANSFER_INDEX` UNIQUE (`CI`, `TFF`);