
ALTER TABLE `DATA_ACCELERATION`
	ADD COLUMN `MOLD_ID` datetime AFTER `DATA_ID`;

ALTER TABLE `DATA_ACCELERATION`
	ADD COLUMN `UPDATED_AT` datetime AFTER `CREATED_AT`;

ALTER TABLE `DATA_ACCELERATION`
	ADD COLUMN `PROC_STATUS` varchar(20) default 'CREATED' AFTER `PROC_CHANGED`;

ALTER TABLE `DATA_ACCELERATION`
	ADD COLUMN `PROC_ERROR_ID` bigint AFTER `PROC_STATUS`;

CREATE INDEX IX_DATA_ACCELERATION_01 ON DATA_ACCELERATION (
	MOLD_ID,
	PROC_STATUS
);

CREATE INDEX IX_DATA_ACCELERATION_02 ON DATA_ACCELERATION (
	PROC_STATUS
);
