BEGIN;
UPDATE `MENU` SET `POSITION` = 1 WHERE `ID` = 1200;
UPDATE `MENU` SET `POSITION` = 2 WHERE `ID` = 1300;
UPDATE `MENU` SET `POSITION` = 3 WHERE `ID` = 1400;

UPDATE `MENU` SET `POSITION` = 1 WHERE `ID` = 2600;
UPDATE `MENU` SET `POSITION` = 2 WHERE `ID` = 2200;
UPDATE `MENU` SET `POSITION` = 3 WHERE `ID` = 2300;

UPDATE `MENU` SET `POSITION` = 1 WHERE `ID` = 1120;

UPDATE `MENU` SET `POSITION` = 1 WHERE `ID` = 1220;
UPDATE `MENU` SET `POSITION` = 2 WHERE `ID` = 1230;
UPDATE `MENU` SET `POSITION` = 3 WHERE `ID` = 1240;
UPDATE `MENU` SET `POSITION` = 4 WHERE `ID` = 1250;
UPDATE `MENU` SET `POSITION` = 5 WHERE `ID` = 1260;
UPDATE `MENU` SET `POSITION` = 6 WHERE `ID` = 1270;
UPDATE `MENU` SET `POSITION` = 7 WHERE `ID` = 1280;
UPDATE `MENU` SET `POSITION` = 8 WHERE `ID` = 1290;
UPDATE `MENU` SET `POSITION` = 9 WHERE `ID` = 1211;

UPDATE `MENU` SET `POSITION` = 1 WHERE `ID` = 1320;
UPDATE `MENU` SET `POSITION` = 2 WHERE `ID` = 1330;
UPDATE `MENU` SET `POSITION` = 3 WHERE `ID` = 1340;
UPDATE `MENU` SET `POSITION` = 4 WHERE `ID` = 1350;
UPDATE `MENU` SET `POSITION` = 5 WHERE `ID` = 1360;
UPDATE `MENU` SET `POSITION` = 6 WHERE `ID` = 1370;
UPDATE `MENU` SET `POSITION` = 7 WHERE `ID` = 1380;

UPDATE `MENU` SET `POSITION` = 1 WHERE `ID` = 2620;

UPDATE `MENU` SET `POSITION` = 1 WHERE `ID` = 2220;
UPDATE `MENU` SET `POSITION` = 2 WHERE `ID` = 2230;
UPDATE `MENU` SET `POSITION` = 3 WHERE `ID` = 2240;
UPDATE `MENU` SET `POSITION` = 4 WHERE `ID` = 2250;
UPDATE `MENU` SET `POSITION` = 5 WHERE `ID` = 2255;
UPDATE `MENU` SET `POSITION` = 6 WHERE `ID` = 2260;
UPDATE `MENU` SET `POSITION` = 7 WHERE `ID` = 2270;

UPDATE `MENU` SET `POSITION` = 1 WHERE `ID` = 2340;
UPDATE `MENU` SET `POSITION` = 2 WHERE `ID` = 2350;

UPDATE `MENU` SET `POSITION` = 1 WHERE `ID` = 4120;

UPDATE `MENU` SET `POSITION` = 1 WHERE `ID` = 5120;
UPDATE `MENU` SET `POSITION` = 2 WHERE `ID` = 5130;
UPDATE `MENU` SET `POSITION` = 3 WHERE `ID` = 5140;

UPDATE `MENU` SET `POSITION` = 1 WHERE `ID` = 6120;
UPDATE `MENU` SET `POSITION` = 2 WHERE `ID` = 6140;
UPDATE `MENU` SET `POSITION` = 3 WHERE `ID` = 6150;
COMMIT;