DROP PROCEDURE IF EXISTS `INSERT_CUSTOM_VALUE_DEFAULT`;
-- DELIMITER #
//
CREATE PROCEDURE `INSERT_CUSTOM_VALUE_DEFAULT`()
BEGIN
IF
(
SELECT COUNT(*)
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = N'CUSTOM_FIELD_VALUE') >0
THEN
ALTER TABLE CUSTOM_FIELD_VALUE MODIFY COLUMN ID BIGINT(20) AUTO_INCREMENT;
INSERT INTO CUSTOM_FIELD_VALUE(OBJECT_ID, CUSTOM_FIELD_ID, VALUE,CREATED_AT)
SELECT MID, CFID, NULL, NOW()
FROM (
         SELECT C.ID CFID, M.ID MID, CFV.ID CFVID
         FROM CUSTOM_FIELD AS C
                  JOIN MOLD M ON C.OBJECT_TYPE='TOOLING'
                  LEFT OUTER JOIN CUSTOM_FIELD_VALUE CFV ON M.ID = CFV.OBJECT_ID
         WHERE CFV.ID IS NULL
         UNION
         SELECT C.ID CFID, M.ID MID, CFV.ID CFVID
         FROM CUSTOM_FIELD AS C
                  JOIN PART M ON C.OBJECT_TYPE='PART'
                  LEFT OUTER JOIN CUSTOM_FIELD_VALUE CFV ON M.ID = CFV.OBJECT_ID
         WHERE CFV.ID IS NULL
     ) AS J;
END IF;
END
//

-- DELIMITER ;