BEGIN;
DELETE FROM GENERAL_CONFIG WHERE ID NOT IN (
    SELECT TBL.MAX_ID FROM (
                               SELECT MAX(G.ID) MAX_ID FROM GENERAL_CONFIG G
                               GROUP BY G.CONFIG_CATEGORY, G.FIELD_NAME) AS TBL
) ;
COMMIT;