package saleson.common;

import saleson.enums.UserType;

public class ApiControllerTest extends BaseControllerTest {
	/**
	 * BearerToken 가져오기
	 * @param userType
	 * @return
	 * @throws Exception
	 */
	protected String getBearerToken(UserType userType) throws Exception {
		return "Bearer " + getAccessToken(userType);
	}


	/**
	 * AccessToken 조회
	 * @param userType
	 * @return
	 * @throws Exception
	 */
	protected String getAccessToken(UserType userType) throws Exception {
		return "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic2FsZXNvbi1hcGkyIiwic2FsZXNvbi1hcGkiXSwiQUNDT1VOVCI6eyJjcmVhdGVkIjpudWxsLCJ1cGRhdGVkIjpudWxsLCJjcmVhdGVkSWQiOm51bGwsImNyZWF0ZWRCeSI6bnVsbCwidXBkYXRlZElkIjpudWxsLCJ1cGRhdGVkQnkiOm51bGwsImlkIjoyLCJhY2NvdW50VHlwZSI6IlVTRVIiLCJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6IntiY3J5cHR9JDJhJDEwJEVPczhWUk9iMTRlN1pueWR2WEVDQS40TG9JaFBPb0ZIS3ZWRi9pQlova2VyMTdFb2N6NFZpIiwibmFtZSI6IuqzoOqwnSIsImF1dGhGYWlsdXJlQ291bnQiOjAsImFjY291bnRTdGF0dXMiOiJFTkFCTEVEIiwicm9sZXMiOlt7ImNyZWF0ZWQiOm51bGwsInVwZGF0ZWQiOm51bGwsImNyZWF0ZWRJZCI6bnVsbCwiY3JlYXRlZEJ5IjpudWxsLCJ1cGRhdGVkSWQiOm51bGwsInVwZGF0ZWRCeSI6bnVsbCwiaWQiOjIsIm5hbWUiOiJST0xFX1VTRVIiLCJkZXNjcmlwdGlvbiI6bnVsbH1dLCJhY2NvdW50Tm9uRXhwaXJlZCI6dHJ1ZSwiYWNjb3VudE5vbkxvY2tlZCI6dHJ1ZSwiY3JlZGVudGlhbHNOb25FeHBpcmVkIjp0cnVlLCJlbmFibGVkIjp0cnVlfSwiQUNDT1VOVF9JRCI6MiwidXNlcl9uYW1lIjoidXNlciIsInNjb3BlIjpbInJvbGVfdXNlciJdLCJleHAiOjE1NTkwMjAzNjYsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiIyODE1NDRhZi03OTVkLTRmMmItODMyNi1lMjMwY2JiZjQxMGYiLCJjbGllbnRfaWQiOiJzYWxlc29uLW1hbmFnZXIifQ.U9ZUTt3GLe6UPAkWPoPw0SlUQfAlKl_3PNiyvO0CpNKxPYaUIf7t4ZeId0xByTp8oxmkGscDBw47HcyomeMR67HWI4MwQK7W9-zkT_RyLu1vYakXA_S9q4wxnhszl84puJSb1qKie2Cn29_LqJfXSERNF_gESEoW4DemCzgG0RaN_JO7o_1x_C78MS5rRvgPWMjqwFC3MA4sul4v1gUYMHXKTYw1tDADpSBcp2U3nycVPXUjGOD0PgSzobxRjcLsL0qYF5wmMcOQYVDg3NLMRxMmkqI3CxujI-EFuJ_q0JAQOEVD_mawD8Sor72RaQ_l-k7KSKHJL6Mf_FTyKXpXog";
	}
}
